name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv lock --check
      - run: uv sync --locked --all-extras --dev
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run basedpyright
      - run: uv run pytest
